Fix failed Approve Policies status check when pre workflow hook fails
lyft/atlantis pull request #339
Opened 2022-09-12 18:10 UTC by Aayyush

In this PR, we replace the Policy Check command with Approve Policies when pre workflow hook fails since we don't support Approve Policies commit statuses.

2022-09-12 19:04 UTC, samrabelachew approved these changes

2022-09-12 19:33 UTC, nishkrishnan requested changes

2022-09-12 19:33 UTC, nishkrishnan commented on server/events/command_runner.go
> +			cmd.Name = command.PolicyCheck
cmd is a pointer I think this is not what we want. This is what i mentioned to you before.

2022-09-26 18:42 UTC, nishkrishnan approved these changes

2022-09-26 20:13 UTC, merged